=== clifcliftonton/xml-basics/data/timetable.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!--Timetable-->

<!--Instructors-->
<!ELEMENT instructors (instructor *)>
<!ELEMENT instructor (class *)>
<!ATTLIST instructor code #REQUIRED>

<!--Periods-->
<!ELEMENT periods (period *)>
<!ELEMENT period (class *)>
<!ATTLIST period type (830|930|1030|1130|1230|1330|1430|1530) #REQUIRED>

<!--Days-->
<!ELEMENT days (day *)>
<!ELEMENT day (class *)>
<!ATTLIST day type (Monday|Tuesday|Wednesday|Thursday|Friday) #REQUIRED>

<!--Class-->
<!ELEMENT class (name|code|day|time|location|type)*>
<!ELEMENT class (
        name?,
        code?,
        day?,
        time?,
        location?,
        type?,
        instructor?
        )>
<!ELEMENT instructor (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT code (#PCDATA)>
<!ELEMENT day (#PCDATA)>
<!ELEMENT time (#PCDATA)>
<!ELEMENT location (#PCDATA)>
<!ELEMENT type type (Lab|Lecture)>

=== clifcliftonton/xml-basics/data/instructors.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE instructors SYSTEM "timetable.dtd">
<!--
Set 4G schedule by instructor
-->
<instructors>
    <instructor type="Brenda Fine">
        <class>
            <name>Computer Graphics</name>
            <code>COMP4560</code>
            <day1>Monday</day1>
            <time>8:30 - 10:20</time>
            <location>SE12-320</location>
            <type>Lab</type>
        </class>
        <class>
            <name>Computer Graphics</name>
            <code>COMP4560</code>
            <day1>Tuesday</day1>
            <time>11:30 - 12:20</time>
            <location>SW5-1850</location>
            <type>Lecture</type>
        </class>
        <class>
            <name>Computer Graphics</name>
            <code>COMP4560</code>
            <day1>Friday</day1>
            <time>12:30 - 1:20</time>
            <location>SW3-1750</location>
            <type>Lecture</type>
        </class>
    </instructor>

    <instructor type="Mirela Gutica">
        <class>
            <name>Operating Systems</name>
            <code>COMP4735</code>
            <day1>Monday</day1>
            <time>11:30 - 12:20</time>
            <location>SW1-1205</location>
            <type>Lecture</type>
        </class>
        <class>
            <name>Operating Systems</name>
            <code>COMP4735</code>
            <day1>Wednesday</day1>
            <time>1:30 - 2:20</time>
            <location>SW1-1205</location>
            <type>Lecture</type>
        </class>
        <class>
            <name>Operating Systems</name>
            <code>COMP4735</code>
            <day1>Thursday</day1>
            <time>11:30 - 12:20</time>
            <location>SW3-1710</location>
            <type>Lecture</type>
        </class>
    </instructor>

    <instructor type="Mathew Linder">
    <class>
        <name>Operating Systems</name>
        <code>COMP4735</code>
        <day1>Monday</day1>
        <time>3:30 - 5:20</time>
        <location>SW3-1710</location>
        <type>Lab</type>
    </class>
    </instructor>

    <instructor type="James Parry">
        <class>
            <name>Software Development</name>
            <code>COMP4711</code>
            <day1>Tuesday</day1>
            <time>12:30 - 2:20</time>
            <location>SE12-320</location>
            <type>Lab</type>
        </class>
        <class>
            <name>Software Development</name>
            <code>COMP4711</code>
            <day1>Tuesday</day1>
            <time>12:30 - 2:20</time>
            <location>SW5-1840</location>
            <type>Lecture</type>
        </class>
    </instructor>

    <instructor type="Tejinder Randhawa">
        <class>
            <name>Client Server Special Topics</name>
            <code>COMP4945</code>
            <day1>Wednesday</day1>
            <time>9:30 - 10:20</time>
            <location>SE12-319</location>
            <type>Lecture</type>
        </class>
        <class>
            <name>Client Server 2</name>
            <code>COMP4941</code>
            <day1>Wednesday</day1>
            <time>10:30 - 11:20</time>
            <location>SE12-319</location>
            <type>Lab</type>
        </class>
        <class>
            <name>Client Server Special Topics</name>
            <code>COMP4945</code>
            <day1>Thursday</day1>
            <time>1:30 - 5:20</time>
            <location>SE12-319</location>
            <type>Lab</type>
        </class>
        <class>
            <name>Client Server 2</name>
            <code>COMP4941</code>
            <day1>Friday</day1>
            <time>1:30 - 5:20</time>
            <location>SE12-319</location>
            <type>Lab</type>
        </class>
    </instructor>

    <instructor type="Catherine Ryan">
        <class>
            <name>Business Law</name>
            <code>BLAW3600</code>
            <day1>Thursday</day1>
            <time>9:30 - 11:20</time>
            <location>SW3-2620</location>
            <type>Lab</type>
        </class>
        <class>
            <name>Business Law</name>
            <code>BLAW3600</code>
            <day1>Friday</day1>
            <time>8:30 - 10:20</time>
            <location>SW5-1840</location>
            <type>Lecture</type>
        </class>
    </instructor>
</instructors>

=== clifcliftonton/xml-basics/data/days.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE days SYSTEM "timetable.dtd">
<!--
Set 4G schedule by day
-->

<days>
    <day type="Monday">
        <class>
            <name>Computer Graphics</name>
            <code>COMP4560</code>
            <instructor1>Brenda Fine</instructor1>
            <time>8:30 - 10:20</time>
            <location>SE12-320</location>
            <type>Lab</type>
        </class>
        <class>
            <name>Operating Systems</name>
            <code>COMP4735</code>
            <instructor1>Mirela Gutica</instructor1>
            <time>11:30 - 12:20</time>
            <location>SW1-1205</location>
            <type>Lecture</type>
        </class>
        <class>
            <name>Operating Systems</name>
            <code>COMP4735</code>
            <instructor1>Mathew Linder</instructor1>
            <time>3:30 - 5:20</time>
            <location>SW3-1710</location>
            <type>Lab</type>
        </class>
    </day>

    <day type="Tuesday">
        <class>
            <name>Computer Graphics</name>
            <code>COMP4560</code>
            <instructor1>Brenda Fine</instructor1>
            <time>11:30 - 12:20</time>
            <location>SW5-1850</location>
            <type>Lecture</type>
        </class>
        <class>
            <name>Software Development</name>
            <code>COMP4711</code>
            <instructor1>James Parry</instructor1>
            <time>12:30 - 2:20</time>
            <location>SE12-320</location>
            <type>Lab</type>
        </class>
        <class>
            <name>Software Development</name>
            <code>COMP4711</code>
            <instructor1>James Parry</instructor1>
            <time>12:30 - 2:20</time>
            <location>SW5-1840</location>
            <type>Lecture</type>
        </class>
    </day>

    <day type="Wednesday">
        <class>
            <name>Client Server Special Topics</name>
            <code>COMP4945</code>
            <instructor1>Tejinder Randhawa</instructor1>
            <time>9:30 - 10:20</time>
            <location>SE12-319</location>
            <type>Lecture</type>
        </class>
        <class>
            <name>Client Server 2</name>
            <code>COMP4941</code>
            <instructor1>Tejinder Randhawa</instructor1>
            <time>10:30 - 11:20</time>
            <location>SE12-319</location>
            <type>Lab</type>
        </class>
        <class>
            <name>Operating Systems</name>
            <code>COMP4735</code>
            <instructor1>Mirela Gutica</instructor1>
            <time>1:30 - 2:20</time>
            <location>SW1-1205</location>
            <type>Lecture</type>
        </class>
    </day>

    <day type="Thursday">
        <class>
            <name>Business Law</name>
            <code>BLAW3600</code>
            <instructor1>Catherine Ryan</instructor1>
            <time>9:30 - 11:20</time>
            <location>SW3-2620</location>
            <type>Lab</type>
        </class>
        <class>
            <name>Operating Systems</name>
            <code>COMP4735</code>
            <instructor1>Mirela Gutica</instructor1>
            <time>11:30 - 12:20</time>
            <location>SW3-1710</location>
            <type>Lecture</type>
        </class>
        <class>
            <name>Client Server Special Topics</name>
            <code>COMP4945</code>
            <instructor1>Tejinder Randhawa</instructor1>
            <time>1:30 - 5:20</time>
            <location>SE12-319</location>
            <type>Lab</type>
        </class>
    </day>

    <day type="Friday">
        <class>
            <name>Business Law</name>
            <code>BLAW3600</code>
            <instructor1>Catherine Ryan</instructor1>
            <time>8:30 - 10:20</time>
            <location>SW5-1840</location>
            <type>Lecture</type>
        </class>
        <class>
            <name>Computer Graphics</name>
            <code>COMP4560</code>
            <instructor1>Brenda Fine</instructor1>
            <time>12:30 - 1:20</time>
            <location>SW3-1750</location>
            <type>Lecture</type>
        </class>
        <class>
            <name>Client Server 2</name>
            <code>COMP4941</code>
            <instructor1>Tejinder Randhawa</instructor1>
            <time>1:30 - 5:20</time>
            <location>SE12-319</location>
            <type>Lab</type>
        </class>
    </day>
</days>
